/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author crist
 */
public class ConsultaSeleccionarBusqueda extends javax.swing.JFrame {

    private TramitarDocumentos principal;
    /**
     * Creates new form ConsultaSeleccionarBusqueda
     */
    public ConsultaSeleccionarBusqueda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultasBusquedaPanel = new javax.swing.JPanel();
        buscarFechaNBoton = new javax.swing.JButton();
        buscarNombreBoton = new javax.swing.JButton();
        buscarCurpBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        consultasBusquedaPanel.setBackground(new java.awt.Color(255, 255, 255));

        buscarFechaNBoton.setBackground(new java.awt.Color(102, 102, 102));
        buscarFechaNBoton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        buscarFechaNBoton.setForeground(new java.awt.Color(255, 255, 255));
        buscarFechaNBoton.setText("Buscar por fecha N");
        buscarFechaNBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarFechaNBotonActionPerformed(evt);
            }
        });

        buscarNombreBoton.setBackground(new java.awt.Color(102, 102, 102));
        buscarNombreBoton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        buscarNombreBoton.setForeground(new java.awt.Color(255, 255, 255));
        buscarNombreBoton.setText("Buscar por nombre");
        buscarNombreBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarNombreBotonActionPerformed(evt);
            }
        });

        buscarCurpBoton.setBackground(new java.awt.Color(102, 102, 102));
        buscarCurpBoton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        buscarCurpBoton.setForeground(new java.awt.Color(255, 255, 255));
        buscarCurpBoton.setText("Buscar por curp");
        buscarCurpBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCurpBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consultasBusquedaPanelLayout = new javax.swing.GroupLayout(consultasBusquedaPanel);
        consultasBusquedaPanel.setLayout(consultasBusquedaPanelLayout);
        consultasBusquedaPanelLayout.setHorizontalGroup(
            consultasBusquedaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultasBusquedaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buscarNombreBoton)
                .addGap(37, 37, 37)
                .addComponent(buscarCurpBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(buscarFechaNBoton))
        );
        consultasBusquedaPanelLayout.setVerticalGroup(
            consultasBusquedaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultasBusquedaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(consultasBusquedaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarFechaNBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarCurpBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarNombreBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(consultasBusquedaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(consultasBusquedaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarFechaNBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarFechaNBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarFechaNBotonActionPerformed

    private void buscarCurpBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCurpBotonActionPerformed

         principal.contenido.removeAll();
        ConsultasCurp busquedaCurp = new ConsultasCurp();
        principal.contenido.add(busquedaCurp.traerContenido());
        
        principal.contenido.revalidate();
        principal.contenido.repaint();
    }//GEN-LAST:event_buscarCurpBotonActionPerformed

    private void buscarNombreBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarNombreBotonActionPerformed
       principal.contenido.removeAll();
        ConsultasNombre busquedaNombre = new ConsultasNombre();
        principal.contenido.add(busquedaNombre.traerContenido());
        
        principal.contenido.revalidate();
        principal.contenido.repaint();
    }//GEN-LAST:event_buscarNombreBotonActionPerformed
  public javax.swing.JPanel traerContenido() {
        return this.consultasBusquedaPanel;
    }
    
    public void posicion(TramitarDocumentos documentos){
    this.principal = documentos;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarCurpBoton;
    private javax.swing.JButton buscarFechaNBoton;
    private javax.swing.JButton buscarNombreBoton;
    private javax.swing.JPanel consultasBusquedaPanel;
    // End of variables declaration//GEN-END:variables
}
