/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author tacot
 */
public class ReporteSeleccionarBusqueda extends javax.swing.JFrame {

    private TramitarDocumentos principal;
    /**
     * Creates new form ReporteSeleccionarBusqueda
     */
    public ReporteSeleccionarBusqueda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenido = new javax.swing.JPanel();
        botonBperiodo = new javax.swing.JButton();
        botonBtipo = new javax.swing.JButton();
        botonBnombre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenido.setBackground(new java.awt.Color(255, 255, 255));
        contenido.setPreferredSize(new java.awt.Dimension(540, 55));

        botonBperiodo.setBackground(new java.awt.Color(102, 102, 102));
        botonBperiodo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        botonBperiodo.setForeground(new java.awt.Color(255, 255, 255));
        botonBperiodo.setText("Buscar por periodo");
        botonBperiodo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonBperiodo.setBorderPainted(false);
        botonBperiodo.setFocusPainted(false);
        botonBperiodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBperiodoActionPerformed(evt);
            }
        });

        botonBtipo.setBackground(new java.awt.Color(102, 102, 102));
        botonBtipo.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        botonBtipo.setForeground(new java.awt.Color(255, 255, 255));
        botonBtipo.setText("Buscar por tipo ");
        botonBtipo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonBtipo.setBorderPainted(false);
        botonBtipo.setFocusPainted(false);
        botonBtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBtipoActionPerformed(evt);
            }
        });

        botonBnombre.setBackground(new java.awt.Color(102, 102, 102));
        botonBnombre.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        botonBnombre.setForeground(new java.awt.Color(255, 255, 255));
        botonBnombre.setText("Buscar por nombre");
        botonBnombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonBnombre.setBorderPainted(false);
        botonBnombre.setFocusPainted(false);
        botonBnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBnombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonBnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(botonBperiodo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(botonBtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBperiodo, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(botonBtipo, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(botonBnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBperiodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBperiodoActionPerformed
        principal.contenido.removeAll();
        ReporteConsultaPeriodo busquedaP = new ReporteConsultaPeriodo();
        principal.contenido.add(busquedaP.traerContenido());
        
        principal.contenido.revalidate();
        principal.contenido.repaint();
    }//GEN-LAST:event_botonBperiodoActionPerformed

    private void botonBtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBtipoActionPerformed
        principal.contenido.removeAll();
        ReporteConsultaTipo busquedaT = new ReporteConsultaTipo();
        principal.contenido.add(busquedaT.traerContenido());
        
        principal.contenido.revalidate();
        principal.contenido.repaint();
    }//GEN-LAST:event_botonBtipoActionPerformed

    private void botonBnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBnombreActionPerformed
        principal.contenido.removeAll();
        ReporteConsultaNombre busquedaNombre = new ReporteConsultaNombre();
        principal.contenido.add(busquedaNombre.traerContenido());
        
        principal.contenido.revalidate();
        principal.contenido.repaint();
    }//GEN-LAST:event_botonBnombreActionPerformed
    
    public javax.swing.JPanel traerContenido() {
        return this.contenido;
    }
    
    public void posicion(TramitarDocumentos documentos){
    this.principal = documentos;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBnombre;
    private javax.swing.JButton botonBperiodo;
    private javax.swing.JButton botonBtipo;
    private javax.swing.JPanel contenido;
    // End of variables declaration//GEN-END:variables
}
