/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author tacot
 */
public class ReporteSeleccionarBusqueda extends javax.swing.JFrame {

    private TramitarDocumentos principal;
    /**
     * Creates new form ReporteSeleccionarBusqueda
     */
    public ReporteSeleccionarBusqueda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenido = new javax.swing.JPanel();
        botonBcurp = new javax.swing.JButton();
        botonBfechaN = new javax.swing.JButton();
        botonBnombre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenido.setBackground(new java.awt.Color(255, 255, 255));
        contenido.setPreferredSize(new java.awt.Dimension(540, 55));

        botonBcurp.setBackground(new java.awt.Color(102, 102, 102));
        botonBcurp.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        botonBcurp.setForeground(new java.awt.Color(255, 255, 255));
        botonBcurp.setText("Buscar por curp");
        botonBcurp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonBcurp.setBorderPainted(false);
        botonBcurp.setFocusPainted(false);
        botonBcurp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBcurpActionPerformed(evt);
            }
        });

        botonBfechaN.setBackground(new java.awt.Color(102, 102, 102));
        botonBfechaN.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        botonBfechaN.setForeground(new java.awt.Color(255, 255, 255));
        botonBfechaN.setText("Buscar por fecha N");
        botonBfechaN.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonBfechaN.setBorderPainted(false);
        botonBfechaN.setFocusPainted(false);
        botonBfechaN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBfechaNActionPerformed(evt);
            }
        });

        botonBnombre.setBackground(new java.awt.Color(102, 102, 102));
        botonBnombre.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        botonBnombre.setForeground(new java.awt.Color(255, 255, 255));
        botonBnombre.setText("Buscar por nombre");
        botonBnombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonBnombre.setBorderPainted(false);
        botonBnombre.setFocusPainted(false);
        botonBnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBnombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonBnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(botonBcurp, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(botonBfechaN, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBcurp, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(botonBfechaN, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(botonBnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBcurpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBcurpActionPerformed
        principal.contenido.removeAll();
        ReporteConsultaCurp busquedaCurp = new ReporteConsultaCurp();
        principal.contenido.add(busquedaCurp.traerContenido());
        
        principal.contenido.revalidate();
        principal.contenido.repaint();
    }//GEN-LAST:event_botonBcurpActionPerformed

    private void botonBfechaNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBfechaNActionPerformed
        principal.contenido.removeAll();
        ReporteConsultaFN busquedaFN = new ReporteConsultaFN();
        principal.contenido.add(busquedaFN.traerContenido());
        
        principal.contenido.revalidate();
        principal.contenido.repaint();
    }//GEN-LAST:event_botonBfechaNActionPerformed

    private void botonBnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBnombreActionPerformed
        principal.contenido.removeAll();
        ReporteConsultaNombre busquedaNombre = new ReporteConsultaNombre();
        principal.contenido.add(busquedaNombre.traerContenido());
        
        principal.contenido.revalidate();
        principal.contenido.repaint();
    }//GEN-LAST:event_botonBnombreActionPerformed
    
    public javax.swing.JPanel traerContenido() {
        return this.contenido;
    }
    
    public void posicion(TramitarDocumentos documentos){
    this.principal = documentos;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBcurp;
    private javax.swing.JButton botonBfechaN;
    private javax.swing.JButton botonBnombre;
    private javax.swing.JPanel contenido;
    // End of variables declaration//GEN-END:variables
}
